# -*- coding: utf-8 -*-
"""summer training 11 july.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JChSOTk331plVKKmDeoQ9zQDXnTuUgNh

while loop
"""

while True:
  str = input('enter string: ')
  if str == "q":
    print('exited loop')
    break
  else:
    print("you typed: ", str)

"""check password using while loop

"""

password = "abc@123"
attempt = 3
while attempt>0:
  user_input = input("enter password: ")
  if user_input == password:
    print("Access granted")
    break
  else:
    attempt -= 1
    print(f"wrong password {attempt} attempts left.")

number = int(input("Enter number between 1 to 100: "))
while number <= 100 and number>= 1:
  if number%7 == 0:
    print(number, "divisible by 7")
    break
  else:
    print(number, "not divisible by 7")
    break

"""for loop"""

for i in range(1, 6):
  print("number: ", i)

"""table using for loop"""

num = int(input("enter number: "))
for i in range(1, 11):
  print(num, "X", i, "=", num*i)

password = "abc@123"
attempt = 3
for i in range(attempt):
  num = input("enter password: ")
  if num == password:
    print("Access granted")
    break
  else:
    attempt -= 1
    print(f"wrong password {attempt} attempts left.")

for i in range(1, 6):
  if i == 3:
    continue
  print(i)

for i in range(1, 11):
  if i == 5:
    continue
  if i == 8:
    break
  print("number: ", i)

password = "abc@123"
attempt = 5
for i in range(attempt):
  num = input("enter password: ")
  if num == "forget":
    attempt -= 1
    print(f"{attempt} attempts left.")
    continue
  if num == password:
    print("Access granted")
    break
  else:
    attempt -= 1
    print(f"wrong password {attempt} attempts left.")

strg = "python"
for i in range(len(strg)):
  if strg[i] == "o":
    continue
  if strg[i] == "n":
    break
  print(strg[i])

"""functions"""

def hello():
  print("hello from function")
hello()

def add(a, b):
  print(a+b)
add(10, 5)

def rev(word):
  print(word[::-1])
rev("harman")

