# -*- coding: utf-8 -*-
"""summer training 09 july.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llk3eCjITtI213k_L1pEP3_WAYV40cLQ
"""

x = 10
y = float(x)
print(type(y))
print(type(x))

x = 10
y = 10.5
print(type(x+y))

"""Bill calculater"""

product_name = str(input("enter product name "))
Quantity = float(input("enter quantity "))
price = float(input("enter price "))
print("product_name = ", product_name,", Quantity = ", Quantity, ", price = ", price)
print("Total price of",product_name, " = ", price*Quantity)

"""if statement"""

a = 10
if a<15:
  print("hello")

"""else statement"""

a = 10
if a>15:
  print("hello")
else:
  print('bye')

a = input()
if a[0] == "-":
  print("negative")
else:
  print("positive")

""" is elif statement ques"""

month = input("Enter month name: ")
if month in ["december", "january", "february"]:
    print("Winter")
elif month in ["march", "april", "may"]:
    print("Summer")
elif month in ["june", "july", "august"]:
    print("Monsoon")
elif month in ["september", "october", "november"]:
    print("sharad")
else:
    print("Invalid month name")

vehical_name = input("Enter vehical name: ")
exp_car = "after 20 years"
exp_bike = "after 15 years"
exp_cycle = "after 10 years"
if vehical_name == "car":
  print(vehical_name, "is expire", exp_car)
elif vehical_name == "bike":
  print(vehical_name, "is expire", exp_bike)
elif vehical_name == "cycle":
  print(vehical_name, "is expire", exp_cycle)
else:
   print("unknow vehical name")

"""table using while loop"""

x = int(input("enter no.: "))
i=1
while i<=10:
  print(x , " X ", i, " = ", x*i)
  i=i+1